"""
Core domain models for the healthcare CRM agent.

Every model carries explicit PHI field annotations so the compliance layer
can enforce minimum-necessary access at runtime. Fields are tagged with:
  - PHI: contains protected health information (18 HIPAA identifiers)
  - OPERATIONAL: non-PHI operational data
  - CLINICAL: clinical data (never generated by autonomous agents)

Models use Pydantic v2 with strict validation.
"""

from __future__ import annotations

import uuid
from datetime import datetime, date
from enum import Enum
from typing import Any

from pydantic import BaseModel, Field, field_validator, ConfigDict


# ============================================================================
# PHI Field Classification Enum
# ============================================================================

class PHIType(str, Enum):
    """Classification of every field for HIPAA compliance."""
    PHI = "phi"              # Protected health information
    OPERATIONAL = "operational"  # Non-PHI operational data
    CLINICAL = "clinical"    # Clinical data (requires clinician access only)


# ============================================================================
# Enums
# ============================================================================

class PatientStatus(str, Enum):
    ACTIVE = "active"
    INACTIVE = "inactive"
    DECEASED = "deceased"
    ARCHIVED = "archived"


class AppointmentType(str, Enum):
    """Clinic-defined appointment types. Never freeform clinical description."""
    NEW_PATIENT = "new_patient"
    FOLLOW_UP = "follow_up"
    ANNUAL_PHYSICAL = "annual_physical"
    SICK_VISIT = "sick_visit"
    PROCEDURE = "procedure"
    TELEHEALTH = "telehealth"
    CONSULTATION = "consultation"


class AppointmentStatus(str, Enum):
    SCHEDULED = "scheduled"
    CONFIRMED = "confirmed"
    CHECKED_IN = "checked_in"
    COMPLETED = "completed"
    CANCELLED = "cancelled"
    NO_SHOW = "no_show"


# ============================================================================
# Patient Model
# ============================================================================

class Patient(BaseModel):
    """
    Represents a patient in the practice.

    PHI fields are explicitly annotated so the PHI scope enforcement
    layer can strip fields at runtime based on agent permissions.
    """
    model_config = ConfigDict(extra="forbid")

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    fhir_resource_id: str | None = Field(
        default=None,
        description="FHIR Patient resource ID if synced with EHR",
    )

    # --- Demographics (PHI) ---
    first_name: str = Field(
        min_length=1,
        max_length=100,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    last_name: str = Field(
        min_length=1,
        max_length=100,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    date_of_birth: date = Field(
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    sex: str | None = Field(
        default=None,
        max_length=20,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    gender_identity: str | None = Field(
        default=None,
        max_length=50,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    race: str | None = Field(
        default=None,
        max_length=50,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    ethnicity: str | None = Field(
        default=None,
        max_length=50,
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    # --- Contact (PHI) ---
    phone: str | None = Field(
        default=None,
        max_length=20,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    email: str | None = Field(
        default=None,
        max_length=255,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    preferred_contact_method: str = Field(
        default="phone",
        max_length=20,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    # --- Address (PHI) ---
    street_address: str | None = Field(
        default=None,
        max_length=255,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    city: str | None = Field(
        default=None,
        max_length=100,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    state: str | None = Field(
        default=None,
        max_length=2,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    zip_code: str | None = Field(
        default=None,
        max_length=10,
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    # --- Emergency Contact (PHI) ---
    emergency_contact_name: str | None = Field(
        default=None,
        max_length=200,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    emergency_contact_phone: str | None = Field(
        default=None,
        max_length=20,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    emergency_contact_relationship: str | None = Field(
        default=None,
        max_length=100,
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    # --- Insurance (PHI) ---
    primary_insurance_plan_id: str | None = Field(
        default=None,
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    # --- Preferences (OPERATIONAL) ---
    language: str = Field(
        default="en",
        max_length=10,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    communication_preferences: dict[str, Any] = Field(
        default_factory=dict,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    # --- Metadata ---
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    status: PatientStatus = Field(default=PatientStatus.ACTIVE)

    @field_validator("state")
    @classmethod
    def validate_state_code(cls, v: str | None) -> str | None:
        if v is not None and len(v) != 2:
            raise ValueError("State must be a 2-letter US state code")
        return v


# ============================================================================
# Appointment Model
# ============================================================================

class Appointment(BaseModel):
    """
    Represents a scheduled appointment.

    Only the appointment type and time are stored — never freeform
    clinical reasoning about what the appointment is for.
    """
    model_config = ConfigDict(extra="forbid")

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    fhir_resource_id: str | None = Field(default=None)

    patient_id: str = Field(
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    provider_id: str = Field(
        max_length=100,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    appointment_type: AppointmentType = Field(
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    appointment_type_display: str = Field(
        max_length=100,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
        description="Human-readable display name from clinic configuration",
    )

    start_time: datetime = Field(
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    end_time: datetime = Field(
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    timezone: str = Field(
        default="America/New_York",
        max_length=50,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    location: str | None = Field(
        default=None,
        max_length=200,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    visit_type: str = Field(
        default="in_person",
        max_length=20,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    status: AppointmentStatus = Field(
        default=AppointmentStatus.SCHEDULED,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    # Scheduling metadata
    created_by: str = Field(
        default="system",
        max_length=100,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)

    # No-show prediction
    no_show_risk: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
        description="Predicted no-show probability (0.0–1.0)",
    )

    # Flags requiring HITL
    requires_hitl: bool = Field(
        default=False,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    hitl_reason: str | None = Field(
        default=None,
        max_length=500,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    # Patient linkage (PHI — links patient to this appointment)
    patient_name: str | None = Field(
        default=None,
        max_length=200,
        json_schema_extra={"phi_type": PHIType.PHI},
        description="Included only for agents with patient-name scope",
    )


# ============================================================================
# Insurance Models
# ============================================================================

class InsuranceSubscriber(BaseModel):
    """The primary policyholder (may be different from patient)."""
    model_config = ConfigDict(extra="forbid")

    first_name: str = Field(
        min_length=1,
        max_length=100,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    last_name: str = Field(
        min_length=1,
        max_length=100,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    date_of_birth: date = Field(
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    subscriber_id: str = Field(
        max_length=50,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    group_number: str | None = Field(
        default=None,
        max_length=50,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    relationship_to_patient: str = Field(
        default="self",
        max_length=20,
        json_schema_extra={"phi_type": PHIType.PHI},
    )


class InsurancePlan(BaseModel):
    """
    Represents an insurance plan and eligibility status.

    All fields are PHI because they link patient identity to coverage.
    """
    model_config = ConfigDict(extra="forbid")

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))

    patient_id: str = Field(
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    payer_name: str = Field(
        max_length=200,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    plan_name: str | None = Field(
        default=None,
        max_length=200,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    plan_type: str | None = Field(
        default=None,
        max_length=50,
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    subscriber: InsuranceSubscriber = Field(
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    # Eligibility results (from X12 271)
    eligibility_status: EligibilityStatus | None = Field(
        default=None,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    eligibility_date: date | None = Field(
        default=None,
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    # Benefit details
    copay_amount: float | None = Field(
        default=None,
        ge=0,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    deductible_amount: float | None = Field(
        default=None,
        ge=0,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    deductible_remaining: float | None = Field(
        default=None,
        ge=0,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    out_of_pocket_max: float | None = Field(
        default=None,
        ge=0,
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    # Network status
    network_status: NetworkStatus | None = Field(
        default=None,
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    # Prior auth requirements
    prior_auth_required: bool = Field(
        default=False,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    prior_auth_number: str | None = Field(
        default=None,
        max_length=50,
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    # Metadata
    checked_at: datetime = Field(default_factory=datetime.utcnow)
    raw_271_response: str | None = Field(
        default=None,
        json_schema_extra={"phi_type": PHIType.PHI},
        description="Raw X12 271 response for audit purposes",
    )


class EligibilityStatus(str, Enum):
    ACTIVE = "active"
    INACTIVE = "inactive"
    PENDING = "pending"
    UNKNOWN = "unknown"


class NetworkStatus(str, Enum):
    IN_NETWORK = "in_network"
    OUT_OF_NETWORK = "out_of_network"
    UNKNOWN = "unknown"


# ============================================================================
# Prior Authorization Model
# ============================================================================

class PriorAuthStatus(str, Enum):
    DRAFT = "draft"
    SUBMITTED = "submitted"
    APPROVED = "approved"
    DENIED = "denied"
    PENDING = "pending"
    EXPIRED = "expired"


class PriorAuthorization(BaseModel):
    """
    Prior authorization record.

    CRITICAL: The clinical_justification field is CLINICAL and must be
    authored by a clinician. The system NEVER generates this field autonomously.
    """
    model_config = ConfigDict(extra="forbid")

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))

    patient_id: str = Field(
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    insurance_plan_id: str = Field(
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    # Procedure info (OPERATIONAL — codes and templates, not clinical reasoning)
    procedure_code: str = Field(
        max_length=10,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
        description="CPT/HCPCS procedure code",
    )
    procedure_description: str = Field(
        max_length=500,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    # CLINICAL — clinician-authored only, never system-generated
    clinical_justification: str | None = Field(
        default=None,
        max_length=5000,
        json_schema_extra={"phi_type": PHIType.CLINICAL},
        description="MUST be authored by a clinician. Never system-generated.",
    )
    diagnosing_clinician_id: str | None = Field(
        default=None,
        max_length=100,
        json_schema_extra={"phi_type": PHIType.CLINICAL},
    )

    # Status
    status: PriorAuthStatus = Field(
        default=PriorAuthStatus.DRAFT,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    submitted_at: datetime | None = Field(default=None)
    approved_at: datetime | None = Field(default=None)
    expiration_date: date | None = Field(default=None)

    # Response
    prior_auth_number: str | None = Field(
        default=None,
        max_length=50,
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    denial_reason: str | None = Field(
        default=None,
        max_length=1000,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


# ============================================================================
# Message Model
# ============================================================================

class MessageDirection(str, Enum):
    INBOUND = "inbound"
    OUTBOUND = "outbound"


class MessageChannel(str, Enum):
    SMS = "sms"
    EMAIL = "email"
    VOICE = "voice"
    PORTAL = "portal"


class MessageStatus(str, Enum):
    PENDING = "pending"
    SENT = "sent"
    DELIVERED = "delivered"
    FAILED = "failed"
    BLOCKED = "blocked"  # Blocked by content classifier
    ESCALATED = "escalated"  # Escalated to HITL


class Message(BaseModel):
    """
    Represents a patient communication message.

    Every outbound message passes through the clinical content classifier.
    Messages flagged as clinical are blocked and escalated to HITL.
    """
    model_config = ConfigDict(extra="forbid")

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))

    patient_id: str = Field(
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    direction: MessageDirection = Field(
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    channel: MessageChannel = Field(
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    to_address: str = Field(
        max_length=255,
        json_schema_extra={"phi_type": PHIType.PHI},
        description="Phone number or email — PHI because it identifies the patient",
    )
    body: str = Field(
        max_length=5000,
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    status: MessageStatus = Field(
        default=MessageStatus.PENDING,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    # Content classification results
    clinical_content_detected: bool = Field(
        default=False,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
        description="Set by clinical content classifier",
    )
    classifier_confidence: float | None = Field(
        default=None,
        ge=0.0,
        le=1.0,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    classification_categories: list[str] = Field(
        default_factory=list,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    # HITL
    requires_hitl: bool = Field(
        default=False,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    hitl_reason: str | None = Field(
        default=None,
        max_length=500,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    sent_at: datetime | None = Field(default=None)
    created_at: datetime = Field(default_factory=datetime.utcnow)

    # Campaign linkage (for recall campaigns)
    campaign_id: str | None = Field(
        default=None,
        max_length=100,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )


# ============================================================================
# Referral Model
# ============================================================================

class ReferralStatus(str, Enum):
    PENDING = "pending"
    SENT = "sent"
    COMPLETED = "completed"
    OVERDUE = "overdue"
    CANCELLED = "cancelled"


class Referral(BaseModel):
    """
    Represents a referral to a specialist or external provider.
    """
    model_config = ConfigDict(extra="forbid")

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))

    patient_id: str = Field(
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    referring_provider_id: str = Field(
        max_length=100,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    referred_to_provider_id: str = Field(
        max_length=100,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    referred_to_specialty: str = Field(
        max_length=100,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    referral_reason: str = Field(
        max_length=500,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    status: ReferralStatus = Field(
        default=ReferralStatus.PENDING,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    sent_at: datetime | None = Field(default=None)
    due_date: date | None = Field(
        default=None,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    completed_at: datetime | None = Field(default=None)

    consult_note_received: bool = Field(
        default=False,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    consult_note_id: str | None = Field(
        default=None,
        max_length=100,
        json_schema_extra={"phi_type": PHIType.CLINICAL},
    )

    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)


# ============================================================================
# Intake Summary Model
# ============================================================================

class IntakeStatus(str, Enum):
    IN_PROGRESS = "in_progress"
    COMPLETED = "completed"
    ESCALATED = "escalated"  # Red-flag escalation
    INCOMPLETE = "incomplete"


class IntakeSummary(BaseModel):
    """
    Structured intake result from the IntakeAgent.

    Contains only structured questionnaire responses — never freeform
    clinical Q&A. Red-flag triggers cause immediate escalation.
    """
    model_config = ConfigDict(extra="forbid")

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    patient_id: str = Field(
        json_schema_extra={"phi_type": PHIType.PHI},
    )

    # Structured demographic and insurance data collected during intake
    demographics_verified: bool = Field(
        default=False,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    insurance_verified: bool = Field(
        default=False,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    # Structured medical history (from intake questionnaire form only)
    chief_complaint: str | None = Field(
        default=None,
        max_length=500,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
        description="Patient's stated reason for visit — from structured form only",
    )
    current_medications: list[str] = Field(
        default_factory=list,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    known_allergies: list[str] = Field(
        default_factory=list,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    medical_history_flags: list[str] = Field(
        default_factory=list,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
        description="Structured flags from intake questionnaire (e.g., 'diabetes', 'hypertension')",
    )

    # Red-flag escalation
    red_flag_triggered: bool = Field(
        default=False,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    red_flag_type: str | None = Field(
        default=None,
        max_length=100,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    red_flag_details: str | None = Field(
        default=None,
        max_length=1000,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    status: IntakeStatus = Field(
        default=IntakeStatus.IN_PROGRESS,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    completed_at: datetime | None = Field(default=None)
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ============================================================================
# Encounter Model
# ============================================================================

class Encounter(BaseModel):
    """
    Represents a working encounter — short-term state for active patient interactions.

    PHI scope: contains minimum-necessary PHI for the current interaction.
    Never persisted to long-term memory with PHI.
    """
    model_config = ConfigDict(extra="forbid")

    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    patient_id: str = Field(
        json_schema_extra={"phi_type": PHIType.PHI},
    )
    encounter_type: str = Field(
        max_length=50,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )
    status: str = Field(
        default="active",
        max_length=20,
        json_schema_extra={"phi_type": PHIType.OPERATIONAL},
    )

    # Working data for agents
    intake_summary_id: str | None = Field(default=None)
    appointment_id: str | None = Field(default=None)
    insurance_plan_id: str | None = Field(default=None)

    started_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: datetime | None = Field(default=None)


# ============================================================================
# Clinic Configuration Model
# ============================================================================

class ClinicConfig(BaseModel):
    """
    Clinic-level configuration — no PHI, purely operational.
    """
    model_config = ConfigDict(extra="forbid")

    clinic_name: str = Field(max_length=200)
    timezone: str = Field(default="America/New_York", max_length=50)
    phone: str = Field(max_length=20)
    address: str = Field(max_length=500)

    # Provider configuration
    providers: dict[str, ProviderConfig] = Field(default_factory=dict)

    # Appointment type definitions
    appointment_types: dict[str, AppointmentTypeConfig] = Field(default_factory=dict)

    # Scheduling rules
    scheduling_rules: SchedulingRules = Field(default_factory=lambda: SchedulingRules())

    # Communication settings
    reminder_lead_times_hours: list[int] = Field(default=[24, 2])
    recall_campaigns_enabled: bool = Field(default=True)

    # HITL rules
    hitl_rules: HITLRules = Field(default_factory=lambda: HITLRules())


class ProviderConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    name: str = Field(max_length=200)
    specialty: str = Field(max_length=100)
    max_appointments_per_day: int = Field(default=20, ge=1, le=50)
    appointment_duration_minutes: dict[str, int] = Field(
        default_factory=lambda: {
            AppointmentType.NEW_PATIENT.value: 30,
            AppointmentType.FOLLOW_UP.value: 15,
            AppointmentType.ANNUAL_PHYSICAL.value: 45,
            AppointmentType.SICK_VISIT.value: 15,
        }
    )
    blocked_times: list[TimeBlock] = Field(default_factory=list)


class TimeBlock(BaseModel):
    model_config = ConfigDict(extra="forbid")

    day_of_week: str = Field(max_length=10)  # monday, tuesday, etc.
    start_time: str = Field(max_length=5)  # HH:MM
    end_time: str = Field(max_length=5)


class AppointmentTypeConfig(BaseModel):
    model_config = ConfigDict(extra="forbid")

    display_name: str = Field(max_length=100)
    duration_minutes: int = Field(ge=5, le=120)
    description: str = Field(max_length=500)


class SchedulingRules(BaseModel):
    model_config = ConfigDict(extra="forbid")

    overbook_high_risk_no_show: bool = Field(default=True)
    no_show_risk_threshold: float = Field(default=0.6, ge=0.0, le=1.0)
    max_cancellations_before_hitl: int = Field(default=3, ge=1)
    min_booking_lead_time_hours: int = Field(default=1, ge=0)


class HITLRules(BaseModel):
    model_config = ConfigDict(extra="forbid")

    max_cancellations_before_hitl: int = Field(default=3, ge=1)
    prior_auth_always_requires_hitl: bool = Field(default=True)
    recall_requires_clinician_signoff: bool = Field(default=True)
